services:
  - type: web
    name: converter-feed
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: XIBO_AUTH_URL
        value: https://SEU_DOMINIO_DO_XIBO/api/authorize/access_token
      - key: XIBO_CLIENT_ID
        value: seu_client_id
      - key: XIBO_CLIENT_SECRET
        value: seu_client_secret
      - key: XIBO_DATASET_ID
        value: ID_do_dataset
      - key: XIBO_API_URL
        value: https://SEU_DOMINIO_DO_XIBO/api
      - key: RSS_URL
        value: https://URL_DO_FEED_MAL_FORMATADO
